import Footer from '@/components/Footer'
import Header from '@/components/Header'
import PageProgress from '@/components/PageProgress'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} mx-auto grid grid-rows-[auto_1fr_auto] min-h-screen`}>
				<PageProgress />
				<Header />
				<main className='max-w-5xl mx-auto w-full'>{children}</main>
				<Footer />
			</body>
		</html>
	)
}
