import Footer from '@/components/Footer'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import PageProgress from '@/components/PageProgress'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} max-w-7xl mx-auto grid grid-rows-[auto_1fr_auto] min-h-screen`}
      >
        <PageProgress />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
